name: Apply labels
on:
  pull_request:
    branches: [main, feature-ariel]

jobs:
  label_pr:
    name: Label the PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ariel
  deploy-main:
#     uses: ./.github/workflows/reusable.yml
    uses: arielfenster/github-actions-testing-2/.github/workflows/dummy.yml@main
    secrets: inherit
